ステップ18: 優先順位を設定しよう（※類似した実装経験のある人は省略可）
DaisukeShibuya1006/Task-management-system pull request #19
Opened 2020-10-29 14:23 UTC by DaisukeShibuya1006

## 要件・仕様
- タスクに対して、優先順位（高中低）を登録できるようにしましょう
- 優先順位でソートできるようにしましょう
- system specを拡充しましょう
- PRしてレビューをしてもらったら、リリースしてみましょう（以降続けてください）## 処理概要
## 特記

## 動作確認観点
優先順位ソート前
![スクリーンショット 0002-10-29 17 03 09](https://user-images.githubusercontent.com/46443484/97585975-0e4a2700-1a3d-11eb-8088-785df24b0a3b.png)
優先順位の高いソート後
![スクリーンショット 0002-10-29 17 03 25](https://user-images.githubusercontent.com/46443484/97586060-2e79e600-1a3d-11eb-8fb7-4ff2743e3bca.png)
優先順位の低いソート後
![スクリーンショット 0002-10-29 17 03 38](https://user-images.githubusercontent.com/46443484/97586125-3cc80200-1a3d-11eb-96cb-d9b6f988e4a9.png)

## 参考
https://qiita.com/kurawo___D/items/7604f709a9ec28808540

2020-11-02 05:27 UTC, ymaruyama-bst reviewed
step18で実装しようとしている内容の設計資料ってどこかにありますか？

2020-11-02 05:27 UTC, ymaruyama-bst commented on app/models/task.rb
> +    #このステップより前のステップで下記を記述しました。
このコメントはコードに含めず、PRのコメントとして書いたほうがいいと思います。
後から見たときに何のことなのかがわからなくなるので。

2020-11-02 05:27 UTC, ymaruyama-bst commented on config/routes.rb
> +  get 'priority_sort'=> 'tasks#priority_sort'
そもそもなんですが、ソートってこういうやり方でいいんでしょうか？
このやり方だと検索結果に対してソートすることができなそうな気がしますが。。。

2020-11-02 05:27 UTC, ymaruyama-bst commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
こちらの変更はPRの説明に記載されていなそうですが、どういう意図・内容でしょうか？

2020-11-02 05:47 UTC, DaisukeShibuya1006 commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
docker-compose upをする際に毎回rails db:migrateを行っていたので、効率化できると思い記述しました。

2020-11-02 05:49 UTC, ymaruyama-bst commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
DBに登録されているデータがリセットされているということでしょうか？
それともスキーマの変更を頻繁に行うためにほぼ「毎回」ということでしょうか？

2020-11-02 06:00 UTC, DaisukeShibuya1006 commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
スキーマの変更だと思います！
docker-compose up時にdocker-compose run app rails db:migrateを毎回書かなければならないのでしょうか？

2020-11-02 06:11 UTC, ymaruyama-bst commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
up時に実行されるようにしているということはスキーマを変更する度にコンテナを落とすということでしょうか？

2020-11-02 06:52 UTC, DaisukeShibuya1006 commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
>up時に実行されるようにしているということはスキーマを変更する度にコンテナを落とすということでしょうか？

スキーマの変更はdbを変更した際に起きる現象でしょうか？  


ステップ17まではこういう感じでエラーが出たので、upと同時にbundle exec rails db:migrateを行えるようにしました。
説明が拙くてすみません。

<img width="822" alt="スクリーンショット 2020-11-02 15 45 09" src="https://user-images.githubusercontent.com/46443484/97837924-8442dc80-1d22-11eb-8fb8-4e65bb4474f7.png">
<img width="807" alt="スクリーンショット 2020-11-02 15 45 24" src="https://user-images.githubusercontent.com/46443484/97837928-860ca000-1d22-11eb-868d-71ab138f4698.png">

2020-11-02 06:56 UTC, ymaruyama-bst commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
うーん、、、？
migrationファイルを書いたタイミングでdb:migrateを実行してますか？
何を起因にPendingMigrationErrorが起きるのか知りたいです。

2020-11-02 07:01 UTC, DaisukeShibuya1006 commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
db:migrateは自分で書かないといけない感じですか？
docker-compose.ymlにrails db:migrateを記載したら、docker-compose upで一発だと思って記載しました。

2020-11-05 01:10 UTC, ShintaroSakai commented
所々空白があるのが気になります

<img width="277" alt="スクリーンショット 2020-11-05 10 01 18" src="https://user-images.githubusercontent.com/46952281/98184769-8b4e3280-1f4e-11eb-8428-c5051f3a0359.png">

<img width="482" alt="スクリーンショット 2020-11-05 10 02 55" src="https://user-images.githubusercontent.com/46952281/98184785-8f7a5000-1f4e-11eb-874e-c9f15a6eba83.png">

<img width="490" alt="スクリーンショット 2020-11-05 10 03 03" src="https://user-images.githubusercontent.com/46952281/98184794-9608c780-1f4e-11eb-933c-d907527548fe.png">

<img width="389" alt="スクリーンショット 2020-11-05 10 05 36" src="https://user-images.githubusercontent.com/46952281/98184825-ac168800-1f4e-11eb-863f-ab1d706d1275.png">

インデントは揃えましょう
<img width="548" alt="スクリーンショット 2020-11-05 10 05 15" src="https://user-images.githubusercontent.com/46952281/98184868-c6506600-1f4e-11eb-8ad5-4ce1e906c0c2.png">

行末の無駄な改行は削除しましょう
<img width="557" alt="スクリーンショット 2020-11-05 10 03 56" src="https://user-images.githubusercontent.com/46952281/98184919-e718bb80-1f4e-11eb-8b45-b84a4ccf4680.png">

自分のvscodeがおかしいかもしれないので確認お願いします

2020-11-05 02:49 UTC, DaisukeShibuya1006 commented
@ymaruyama-bst 
>step18で実装しようとしている内容の設計資料ってどこかにありますか？

下記のようにクリックで優先順位をソートできるように考えました。
現在のコードですと、ページ遷移してしまいますので、タスク一覧でソートできるようにしてみます！

![Step18ソート設計図](https://user-images.githubusercontent.com/46443484/98191401-6d87ca00-1f5c-11eb-857e-475ab175da89.jpg)

2020-11-05 02:50 UTC, DaisukeShibuya1006 commented on config/routes.rb
> +  get 'priority_sort'=> 'tasks#priority_sort'
> 所々空白があるのが気になります
> 
> <img alt="スクリーンショット 2020-11-05 10 01 18" width="277" src="https://user-images.githubusercontent.com/46952281/98184769-8b4e3280-1f4e-11eb-8428-c5051f3a0359.png">
> 
> <img alt="スクリーンショット 2020-11-05 10 02 55" width="482" src="https://user-images.githubusercontent.com/46952281/98184785-8f7a5000-1f4e-11eb-874e-c9f15a6eba83.png">
> 
> <img alt="スクリーンショット 2020-11-05 10 03 03" width="490" src="https://user-images.githubusercontent.com/46952281/98184794-9608c780-1f4e-11eb-933c-d907527548fe.png">
> 
> <img alt="スクリーンショット 2020-11-05 10 05 36" width="389" src="https://user-images.githubusercontent.com/46952281/98184825-ac168800-1f4e-11eb-863f-ab1d706d1275.png">
> 
> インデントは揃えましょう
> <img alt="スクリーンショット 2020-11-05 10 05 15" width="548" src="https://user-images.githubusercontent.com/46952281/98184868-c6506600-1f4e-11eb-8ad5-4ce1e906c0c2.png">
> 
> 行末の無駄な改行は削除しましょう
> <img alt="スクリーンショット 2020-11-05 10 03 56" width="557" src="https://user-images.githubusercontent.com/46952281/98184919-e718bb80-1f4e-11eb-8b45-b84a4ccf4680.png">
> 
> 自分のvscodeがおかしいかもしれないので確認お願いします

2020-11-05 08:52 UTC, ShintaroSakai reviewed
コメントしました

2020-11-05 08:52 UTC, ShintaroSakai commented on Gemfile.lock
> +    ast (2.4.1)
このファイルの差分ってはなんですか??

2020-11-05 08:52 UTC, ShintaroSakai commented on config/routes.rb
> +  get 'priority_sort'=> 'tasks#priority_sort'
@DaisukeShibuya1006 
ここってどうなりました??

2020-11-05 08:52 UTC, ShintaroSakai commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
> docker-compose upで一発だと思って記載しました。

毎回upするたびにmigrate走らせるのはよくない気がする
`docker-compose exec app rails db:migrate`をスキーマを変更するタイミングで叩くと問題ある感じですか??

2020-11-05 09:31 UTC, DaisukeShibuya1006 commented
>ここってどうなりました??

検索後に優先順位をソートするように模索してますが、なかなか答えが見つかっていない状況です！

> 毎回upするたびにmigrate走らせるのはよくない気がする
docker-compose exec app rails db:migrateをスキーマを変更するタイミングで叩くと問題ある感じですか??

docker-compose down する際にデータごと消えてしまうので、upする際にmigration errorが出る感じです！
docker-compose.ymlのvolumeで永続化させる必要がありますでしょうか？

2020-11-09 01:18 UTC, DaisukeShibuya1006 commented on config/routes.rb
> +  get 'priority_sort'=> 'tasks#priority_sort'
仕様通りの優先順位ソートはできていますが、検索結果に対するソート方法がわからずに詰まっています！
検索結果後に優先順位ソートしないといけませんでしょうか？

2020-11-09 01:22 UTC, DaisukeShibuya1006 commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
>毎回upするたびにmigrate走らせるのはよくない気がする
docker-compose exec app rails db:migrateをスキーマを変更するタイミングで叩くと問題ある感じですか??


docker-compose downする際にデータが削除され、データの永続化ができていない感じです。docker-compose up時にrails db:migrationを毎回行っていました。docker-compose.ymlのvolumeに原因がありそうなので、他の方法を探ってみます！

2020-11-09 01:49 UTC, ShintaroSakai commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
> docker-compose downする際にデータが削除され、データの永続化ができていない感じです。

downを使っているからじゃない??
停止したいだけなら `docker-compose kill`とか'docker stop コンテナID'とか使えば、データ削除されずにコンテナ停止できると思うよ

https://qiita.com/wasanx25/items/d47caf37b79e855af95f

2020-11-09 02:28 UTC, DaisukeShibuya1006 commented on docker-compose.yml
> +    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
docker-compose stopでコンテナ停止するんですね！いつもデータ削除してました！すみません！

2020-11-09 02:53 UTC, DaisukeShibuya1006 commented on Gemfile.lock
> +    ast (2.4.1)
rubocopを走らせましたが、やっぱり整形をせずにファイルを元の状態に戻したことが影響しているかもしれません。
差分を解消し、Gemfile.lockを元に戻すべきでしょうか？

2020-11-12 09:05 UTC, ymaruyama-bst requested changes
とりあえず確認・修正して欲しいところにコメントしました。

2020-11-12 09:05 UTC, ymaruyama-bst commented on Gemfile.lock
> +    ast (2.4.1)
Gemfileに差分がないのにlockファイルに差分があるのはおかしいので修正してください。

2020-11-12 09:05 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +    @tasks = if params[:title] && params[:status].present?
この検索部分、メソッドチェーン使ってシンプルにかけないですかね？
もう一つ検索項目増やしたらぐちゃぐちゃになりません？

2020-11-12 11:13 UTC, ymaruyama-bst commented
優先度部分って検索パラメータを持ち回したりとかできませんかね？
パフォーマンスとか綺麗さとかを無視すれば、URLに検索条件が含まれているように見えるので、そこにさらにソートキーを付けて検索をするような感じに

2020-11-12 22:51 UTC, DaisukeShibuya1006 commented on Gemfile.lock
> +    ast (2.4.1)
Gemfile.lockを元の状態に戻しました！

2020-11-16 01:21 UTC, ymaruyama-bst commented
ソート、この辺って参考にできないですかね？
https://tbpgr.hatenablog.com/entry/20130813/1376408654

2020-11-30 04:52 UTC, ymaruyama-bst commented
概要に貼られているキャプチャってあってますでしょうか？
先週見たときは一覧形式になっていたかと思いますので、変わっているのであれば更新して欲しいです。

2020-12-03 01:47 UTC, closed without merging