Step18：優先順位を設定しよう（２）
DaisukeShibuya1006/Task-management-system pull request #21
Opened 2020-11-30 09:07 UTC by DaisukeShibuya1006

## 要件・仕様
- タスクに対して、優先順位（高中低）を登録
- 優先順位でソート
- PRしてレビューを後、リリースする

## 処理概要
- tasks/new.html.erbのform_forヘルパー内にf.select :priorityで優先度を登録できる
- tasks/index.html.erbのform_withヘルパー内にf.select :keywordで優先度の"高"、"低"が選択可能
  - tasks_contorller.rbのindexメソッドにタイトル&ステータス検索後の優先度ソートを記載

## 動作確認観点

### 優先度ソート前

<img width="724" alt="優先度ソート前" src="https://user-images.githubusercontent.com/46443484/100588679-7f7b4380-3335-11eb-9a9e-5b10da948d79.png">

### **優先度"低"ソート（ステータス検索なし）**
<img width="734" alt="スクリーンショット 2020-11-30 17 52 26" src="https://user-images.githubusercontent.com/46443484/100588756-95890400-3335-11eb-8f71-601537cdaa5c.png">

### 優先度"高"ソート（ステータス検索なし）
<img width="746" alt="優先度 高い ソート（検索なし）" src="https://user-images.githubusercontent.com/46443484/100588793-a0439900-3335-11eb-99b2-ec0b774c680f.png">

### 優先度"低"ソート（ステータス"未着手"で検索）
<img width="728" alt="優先度 低 ソート（未着手検索）" src="https://user-images.githubusercontent.com/46443484/100588835-aa659780-3335-11eb-81c1-f9424df524fd.png">

### 優先度"高"ソート（ステータス"未着手"で検索）
<img width="740" alt="優先度 高 ソート（未着手検索）" src="https://user-images.githubusercontent.com/46443484/100588881-b81b1d00-3335-11eb-84e3-240147fef9be.png">

2020-12-03 03:35 UTC, ymaruyama-bst commented
rubocopでのチェックって通ってますでしょうか？

2020-12-03 03:54 UTC, DaisukeShibuya1006 commented
> rubocopでのチェックって通ってますでしょうか？

現在確認し、チェックが通りました！

2020-12-03 06:48 UTC, ymaruyama-bst requested changes
とりあえず気になったところにコメントしました。

2020-12-03 06:48 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +      @tasks.all
この部分を通ったときに返されるデータって何になりますか？

2020-12-03 06:48 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
引数の先頭についている`_`ってなんでしょう？

2020-12-03 06:48 UTC, ymaruyama-bst commented on app/views/tasks/index.html.erb
> +   <%= f.select :keyword, [['高', 'high'], ['低', 'low']] %>
ここは`未選択`なしで大丈夫でせようか？

2020-12-03 06:48 UTC, ymaruyama-bst commented on app/views/tasks/index.html.erb
> +   <%= f.select :keyword, [['高', 'high'], ['低', 'low']] %>
後この部分ラベルがないと何の入力が求められているのかがわからないので入れて欲しい。
<img width="381" alt="image" src="https://user-images.githubusercontent.com/46433201/100973525-0c184280-357e-11eb-8f19-774ecbdd0c60.png">

2020-12-03 06:48 UTC, ymaruyama-bst commented on app/views/tasks/index.html.erb
> +            <td><%= task.deadline %></td>
期限の表記を作成日と同じ形にできませんか？
<img width="343" alt="image" src="https://user-images.githubusercontent.com/46433201/100973590-294d1100-357e-11eb-8f90-a4916a6c26e1.png">

2020-12-03 06:48 UTC, ymaruyama-bst commented on app/views/tasks/new.html.erb
> +      <p>進捗</p>
ここってなんでpタグ何でしょうか？
上の部分と違う理由が知りたいです。

2020-12-03 06:48 UTC, ymaruyama-bst commented on app/views/tasks/new.html.erb
> +      <p>進捗</p>
後このページ全体的に内容合ってます？
一部登録ページのラベルと一覧ページの項目名が一致してない気がする。
<img width="265" alt="image" src="https://user-images.githubusercontent.com/46433201/100973887-bdb77380-357e-11eb-8ebb-e98d5fd03b23.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/46433201/100973916-cad46280-357e-11eb-926a-9d8c8dbd14a1.png">

2020-12-03 07:17 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
rubocopで下記のエラーが出たので、rubocopで自動整形させました。(high_low)は未使用のメソッド引数なので、(_)か(_high_low)で記述しなさいと言われたので、(_high_low）にしました。

`Unused method argument - high_low. If it's necessary, use _ or _high_low as an argument name to indicate that it won't be used. You can also write as priority_sort(*) if you want the method to accept any arguments but don't care about them.`

2020-12-03 07:22 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
> (high_low)は未使用のメソッド引数

そうなるとなんで未使用なものが書かれているのかという話になるんですが。。。
今後なにかに使う意図はありますでしょうか？

2020-12-03 07:45 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
使う意図はありません！メソッド引数を削除しても良いですか？

2020-12-03 07:54 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +      @tasks.all
@tasksだと思います。

2020-12-03 08:13 UTC, DaisukeShibuya1006 commented on app/views/tasks/new.html.erb
> +      <p>進捗</p>
> ここってなんでpタグ何でしょうか？
上の部分と違う理由が知りたいです。

違う理由はありません。f.labelに修正しました！

> 後このページ全体的に内容合ってます？
一部登録ページのラベルと一覧ページの項目名が一致してない気がする。

登録ページのラベルが誤っており、"テキスト"から"内容"に変更しました！作成日に関しては、登録時の日時ですので、登録ページに記載しておりません。

2020-12-03 08:20 UTC, DaisukeShibuya1006 commented on app/views/tasks/index.html.erb
> +            <td><%= task.deadline %></td>
期限の表記を修正致しました！

2020-12-03 08:41 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
使わないのであれば消して下さい。

2020-12-03 08:44 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +      @tasks.all
3行目にある`@tasks`と同じですか？
あとこのif文、elseがなくない？

2020-12-03 08:47 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
削除致しました！

2020-12-03 08:54 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +      @tasks.all
３行目と同じです！
elseがないと違和感ありますよね。
elsifをelseで書き直します！

```
if params[:status].present?
      @tasks = @tasks.where('status::text LIKE ?', "%#{params[:status]}%")
    else
      @tasks.all
    end
```

2020-12-03 08:57 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +      @tasks.all
3行目と同じならばここの記述は必要なのでしょうか？
そもそもどういう意図で`.all`をしているのでしょうか？

2020-12-03 09:28 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +      @tasks.all
> 3行目と同じならばここの記述は必要なのでしょうか？
そもそもどういう意図で.allをしているのでしょうか？

改めて考えて、動かしてみましたが必要ないです、すみません。statusが未選択のときに、全件表示をしたかったのですが、上で行っていますよね！    



下記のように修正してみました。こんな感じでよろしいでしょうか？


```
@tasks = params[:title].present? ? Task.where('title LIKE ?', "%#{params[:title]}%") : Task.all
@tasks = params[:status].present? ? @tasks.where('status::text LIKE ?', "%#{params[:status]}%")
```

2020-12-03 09:33 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +      @tasks.all
エラーが出て動かないはずなのでよろしくないです。
修正したらその部分だけでも動作確認して下さい。

2020-12-03 09:36 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +      @tasks.all
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/46433201/100991450-5a394000-3596-11eb-9cdd-43b0d1d55937.png">
そもそもEditorでエラーの警告出たりしないですかね？

2020-12-03 09:45 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +      @tasks.all
動作確認してましたが、接続がうまくいってなかったのか、バグってたのか。
エラー出てきました。すみません。

2020-12-07 02:48 UTC, DaisukeShibuya1006 commented on app/views/tasks/index.html.erb
> +   <%= f.select :keyword, [['高', 'high'], ['低', 'low']] %>
検索項目のラベルを追加しました！

> ここは未選択なしで大丈夫でしょうか？

`   <%= f.select :status, options_for_select([["未選択",""],["未着手","0"],["着手","1"],["完了","2"]])%>
`

未選択なしとは上記のコードのことでしょうか？

2020-12-07 02:56 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +      @tasks.all
こちら修正しましたので、再レビューお願いします！
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/01a35e2f100204fe41d82d2e757191880f6ee098

>そうなるとなんで未使用なものが書かれているのかという話になるんですが。。。
今後なにかに使う意図はありますでしょうか？

priority_sortメソッドの引数を削除しましたが、`priority_sort(params[:keyword])`と呼び出しているのに、メソッドの方で引数がないとおかしいので、再度`priority_sort(high_low)`と致しました。

2020-12-07 03:19 UTC, ymaruyama-bst commented on app/views/tasks/index.html.erb
> +   <%= f.select :keyword, [['高', 'high'], ['低', 'low']] %>
```
<%= f.select :keyword, [['高', 'high'], ['低', 'low']] %>
```
この部分です。
実装上、優先度が未設定の場合の処理もありますが、現状`high`か`low`かを強制的に選ばされることになるので。
https://github.com/DaisukeShibuya1006/Task-management-system/blob/14d79b8091a4d1bf669d884fa151559df77edc6d/app/controllers/tasks_controller.rb#L64

2020-12-07 03:20 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +      @tasks.all
rubocop通ってます？

2020-12-07 04:09 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +      @tasks.all
rubocopを走らせた際に、
「メソッド引数(high_low)が未使用のメソッド引数とされ、メソッド引数を受け入れる場合はpriority_sort(*)と記述することもできる」と指摘を受けますが、priority_sort(high_low)からpriority_sort(*)とするのが適切でしょうか？

2020-12-07 04:13 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
> rubocopを走らせた際に、
「メソッド引数(high_low)が未使用のメソッド引数とされ、メソッド引数を受け入れる場合はpriority_sort(✳︎)と記述することもできる」と指摘を受けますが、priority_sort(high_low)からpriority_sort(✳︎)とするのが適切でしょうか？
Unused method argument - high_low. If it's necessary, use _ or _high_low as an argument name to indicate that it won't be used. You can also write as priority_sort(*) if you want the method to accept any arguments but don't care about them.

こっちでやり取りするべき内容のはずなので移動

2020-12-07 04:14 UTC, DaisukeShibuya1006 commented on app/views/tasks/index.html.erb
> +   <%= f.select :keyword, [['高', 'high'], ['低', 'low']] %>
ご指摘いただいた通り、優先度ソートの未選択項目を追加しました！
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/1ff3f9fc5f60f9065817e6d5e35848d22a8392ab

2020-12-07 04:16 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
これ最初のやり取りに戻ってないですか？
そもそも書いているコードの意味が理解できていない様に見受けられますが、何のために引数を書いているのでしょうか？

2020-12-07 04:22 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +    @tasks = params[:title].present? ? Task.where('title LIKE ?', "%#{params[:title]}%") : Task.all
> @tasks = params[:title].present? ? Task.where('title LIKE ?', "%#{params[:title]}%") : Task.all
@tasks = @tasks.where('status::text LIKE ?', "%#{params[:status]}%") if params[:status].present?

この２つの処理も
priority_sortメソッド同様メソッドで切り出してprivateの下で定義した方がいいね

2020-12-07 04:22 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  def priority_sort(high_low)
コメントで引数がなんなのか書いといた方がいいかも

例
```
優先順位を並べ替えるメソッド
@param [String] 優先順位のソートキー    ←　引数
@return [Object] ソートした結果　←　返り値
```

2020-12-07 04:25 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
セレクトされた優先度から送られてきたデータを受け取り、受け取ったデータを元にソートするためです。

2020-12-07 04:31 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
でもそれ引数を使って実装していないんですよね？

2020-12-07 04:53 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
>そもそも書いているコードの意味が理解できていない様に見受けられますが、何のために引数を書いているのでしょうか？

誤った解釈をしていました、すみません。。。

セレクトされた優先度データはprivate下のpriority_sortで受け取られて、indexメソッド内でpriority_sortが呼び出されているということなんですね。

したがって、private下のメソッドはpriority_sort(high_low)ではなく、priority_sort、
indexメソッド内でもpriority_sort(params[:keyword])ではなく、priority_sortで良い感じですよね？


```
def index
  priority_sort
end

private

def priority_sort
   @tasks = case params[:keyword]
             when 'high'
               @tasks.order('priority')
             when 'low'
               @tasks.order('priority DESC')
             else
               @tasks.order('created_at DESC')
             end
end

```

@tasks = case params[:keyword]でセレクト優先度からデータを受け取っているにも関わらず、理解の浅い記述をしました。すみませんでした！

2020-12-07 04:54 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  def priority_sort(_high_low)
ですね。それであればいいかと思います。

2020-12-07 04:56 UTC, ymaruyama-bst commented
一通り修正が終わりましたら画面も変わっていると思いますので概要に貼られたキャプチャなどの更新をお願いします。

2020-12-07 06:09 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +    @tasks = params[:title].present? ? Task.where('title LIKE ?', "%#{params[:title]}%") : Task.all
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/8ed6ac44db058740726a0036dafa8bdd18bf2cfa

private下にtasks_searchメソッドとしてまとめました！

2020-12-07 06:23 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort(high_low)
承知しました！
high_lowは不要な引数と理解しましたので、次の機会に書いてみます！

2020-12-07 06:40 UTC, DaisukeShibuya1006 commented
> 一通り修正が終わりましたら画面も変わっていると思いますので概要に貼られたキャプチャなどの更新をお願いします。

キャプチャの更新完了しました！

2020-12-07 06:49 UTC, ymaruyama-bst commented
タイトルは検索後もフォームに残るのでしょうか？
それであれば進捗や優先度も検索ボタン押下後も入力した値が保持されるようにした方がいいと思います。
添付のキャプチャを見る限りタイトルだけ残って他は初期表示になっているようなので。
<img width="580" alt="image" src="https://user-images.githubusercontent.com/46433201/101318428-a987b500-38a3-11eb-8ab7-df4ed4ab0ce1.png">

2020-12-07 07:29 UTC, DaisukeShibuya1006 commented
> タイトルは検索後もフォームに残るのでしょうか？
> それであれば進捗や優先度も検索ボタン押下後も入力した値が保持されるようにした方がいいと思います。
> 添付のキャプチャを見る限りタイトルだけ残って他は初期表示になっているようなので。
> <img alt="image" width="580" src="https://user-images.githubusercontent.com/46433201/101318428-a987b500-38a3-11eb-8ab7-df4ed4ab0ce1.png">

進捗と優先度も入力した値が保持されるように設定しました！

2020-12-07 08:58 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +    @tasks = @tasks.where('status::text LIKE ?', "%#{params[:status]}%") if params[:status].present?
ここ処理的に分けて方がいい気がする
```
def tasks_search
    @tasks = params[:title].present? ? Task.where('title LIKE ?', "%#{params[:title]}%") : Task.all
end

def status_search
  @tasks = @tasks.where('status::text LIKE ?', "%#{params[:status]}%") if params[:status].present?
end
```

2020-12-07 09:07 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +    @tasks = @tasks.where('status::text LIKE ?', "%#{params[:status]}%") if params[:status].present?
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/4fb846a9171f089fbcfc11c262bdacfde57968d2

別々で定義しました！

2020-12-07 09:16 UTC, ymaruyama-bst requested changes
気になった箇所にコメントしましたので確認をお願いします。

2020-12-07 09:16 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  def priority_sort
`priority_sort`に`created_at`でのソート文が含まれるのは避けたほうがいいと思います。
メソッド名を`priority`以外にするか、ロジックを変えるかして欲しい。

2020-12-07 09:16 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +    @tasks = @tasks.where('status::text LIKE ?', "%#{params[:status]}%") if params[:status].present?
ここってなんでステータスを`LIKE`で検索しているのでしょうか？
プルダウンでステータスを選択しているのであればLIKE検索をする必要がないように思います。

2020-12-07 10:00 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +    @tasks = @tasks.where('status::text LIKE ?', "%#{params[:status]}%") if params[:status].present?
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/5f06d856bfe92dce6ab4b08b1edc1fb42fdeceb0
こちらでLIKE検索なしのステータス検索に修正しました！

2020-12-07 10:01 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort
`priority_sort`から`tasks_sort`に変更しました！

2020-12-10 01:57 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  def priority_sort(high_low)
> high_lowは不要な引数と理解しましたので、次の機会に書いてみます！

引数があるから書いて欲しいわけじゃなくて、
「このメソッドは何をしているのか」といのを理解して書いているか
が知りたいのでコメントして欲しいと思いました
引数がなければ@paramsは書かなくて、returnだけ書けばいいと思います

2020-12-10 02:30 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort(high_low)
下記のような感じで良いですか？

```
#優先順位を並べ替えるメソッドです
#@return [@tasks] ソートした結果  ←返り値
```

2020-12-10 03:15 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  def priority_sort(high_low)
> 下記のような感じで良いですか？

そうね、上のやつはあくまで例だからそこは自分でよしなに

2020-12-10 03:23 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort(high_low)
コメント追加しました！
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/2ab95218763d8ad076699ced837a0fd022b729dd

2020-12-10 03:26 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +    @tasks = @tasks.where('status = ?', "#{params[:status]}") if params[:status].present?
この部分、`params[:status]`ではなく`"#{params[:status]}"`になっている理由ってなんでしょうか？

2020-12-10 03:38 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +    @tasks = @tasks.where('status = ?', "#{params[:status]}") if params[:status].present?
以前のコードから変更せず、そのままになっていましたので、理由はありません。`params[:status]`に変更しました。

2020-12-10 04:56 UTC, ymaruyama-bst requested changes

2020-12-10 04:56 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
YARDでもRDocでも、どちらでもいいですがDocコメントとしての書き方で書いて欲しいです。
https://qiita.com/kmats@github/items/0c8919a65afbe18e9e37#%E6%AF%94%E8%BC%83

2020-12-10 04:56 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
ちなみにここだけDocコメントが書かれているのってなぜでしょうか？

2020-12-10 04:56 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  def priority_sort(high_low)
title_searchとstatus_searchも書いて欲しい

2020-12-10 05:09 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  def priority_sort(high_low)
コメント２つ追加しました！
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/7087d4f152cca27645f309798dda1edac9867136

2020-12-10 06:13 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
> YARDでもRDocでも、どちらでもいいですがDocコメントとしての書き方で書いて欲しいです。


RDocで下記のような書き方で良いでしょうか？

```
# == Returns:
# @tasksが返り値です
```

2020-12-10 06:18 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
@tasksってなんでしょうか??

Rturnsで返り値であることはわかるから、このメソッドで何を返しているのか
コメントで書いて欲しいです

2020-12-10 06:19 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
上で酒井さんがYARDっぽい書き方を参考として書いているからそちらのほうがいいかも。
YARDの方が見る側としてもわかりやすそうだし。

> 優先順位を並べ替えるメソッド
@param [String] 優先順位のソートキー    ←　引数
@return [Object] ソートした結果　←　返り値

渋谷さんが書いた書き方の場合、Returnsの中に書いているのだから「返り値です」とか書く必要ないし、書くのであればそれがどういうデータかを書くべきかと。

2020-12-10 06:26 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
こういう感じですか？

```
# == Returns:
# formで選択された優先度によって、優先度ソートを返します。
```

2020-12-10 06:27 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
> 優先度ソートを返します。

優先度ソート...ってなんでしょう？

2020-12-10 06:35 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
YARDで書き直してみました。

```
#@return[@tasks] formで選択した優先度を元に、検索結果を昇順か降順で並べ替えます。優先度が未選択の場合、作成日時順に降順します。
```

2020-12-10 06:38 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
一度酒井さんが書いた内容を見直して欲しいですし、それで理解できなければまず調べて下さい。
returnに書くべきはどういうデータが返されるかであって、そのメソッドで何をしているかではないです。

2020-12-10 07:09 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
> 一度酒井さんが書いた内容を見直して欲しいですし、それで理解できなければまず調べて下さい。
returnに書くべきはどういうデータが返されるかであって、そのメソッドで何をしているかではないです。

何度もすみません。returnには返されるデータを書くべきなので、戻り値は「優先順位をソートした結果」なので下記のようになると思います。

```
#@return[@tasks] 優先順位をソートした結果
```

2020-12-10 07:14 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
> @return [戻り値のクラス] 戻り値の説明

https://qiita.com/kmats@github/items/0c8919a65afbe18e9e37#%E6%AF%94%E8%BC%83

'@tasks'ってクラスであってますか??

2020-12-10 07:15 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
一回このメソッドがどういうものなのか、Docコメントには何を書く必要があるかを整理したほうがいい気がします。
きっと酒井さんが丁寧に教えてくれるはず。（自分この後MTGなので）

2020-12-10 09:28 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
こちらって今どういう状況でしょうか？

2020-12-10 09:31 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
酒井さんから教えていただき、たった今コミットしました！
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/7b11c2be929504384a8db3d6bda02c32940e63eb

2020-12-10 09:35 UTC, ShintaroSakai approved these changes
LGTM

2020-12-10 09:38 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
@ShintaroSakai 
> 引数があるから書いて欲しいわけじゃなくて、
「このメソッドは何をしているのか」といのを理解して書いているか
が知りたいのでコメントして欲しいと思いました
引数がなければ@paramsは書かなくて、returnだけ書けばいいと思います

`「このメソッドは何をしているのか」`というメソッドの説明が無いようですがこの内容でいいのでしょうか？
Docコメントとして書き始めたのであればしっかりと書いて欲しいです。

2020-12-10 09:39 UTC, ShintaroSakai approved these changes

2020-12-10 09:54 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
@ymaruyama-bst 
> 「このメソッドは何をしているのか」というメソッドの説明が無いようですがこの内容でいいのでしょうか？

そうですね、
ありがとうございます。見逃してました

@DaisukeShibuya1006 
このメソッドは何をしているのか, も書いていただけると助かります

2020-12-10 10:17 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @tasksが返り値になります
@ymaruyama-bst @ShintaroSakai 

メソッドの処理内容も記載しました。
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/c3cc1267b0313d0a9002c4e3dfb0c6c0f17ffe7a

2020-12-10 10:19 UTC, ymaruyama-bst requested changes

2020-12-10 10:19 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # タスクを優先順位でソートする
以前`priority_sort`のときに指摘したように、必ずしも優先度でソートを掛けているわけではないので、この部分のDocコメントはその部分も考慮して書いて欲しいです。

2020-12-10 10:30 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # タスクを優先順位でソートする
「優先度が未選択なら、作成日順で降順させる」こちらのコメントを追加しました。
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21/commits/e700f0f9df96d4586e88b995bfd1b9dbfcc37ee2

2020-12-10 10:31 UTC, ymaruyama-bst approved these changes
LGTM

2020-12-10 10:32 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # タスクを優先順位でソートする
OKです！
酒井さんが確認して大丈夫そうであればマージしましょう。

2020-12-10 10:34 UTC, ShintaroSakai approved these changes
LGTM

2020-12-10 10:36 UTC, merged