Add_YARD_comment_methods
DaisukeShibuya1006/Task-management-system pull request #27
Opened 2021-02-01 05:13 UTC by DaisukeShibuya1006

## 要件・仕様
- ステップ22までに作成したメソッドにYARDコメントを追加しました。
## 処理概要
- gem install yardでYARDをインストールしました。
- app/controllers/application_controller.rb, app/controllers/sessions_controller.rb,app/controllers/tasks_controller.rbにYARDコメントを追加しました。
## 特記
複雑な処理が含まれる場合は、設計・実装方針を記載してください
※ コードにコメントと言う形での記載も可
## 動作確認観点
実装上、動作確認時に確認すべき箇所がある場合は記載してください
## 参考

2021-02-01 05:15 UTC, ymaruyama-bst commented
参考にしたYARDの書き方ってどちらになりますでしょうか？

2021-02-01 05:16 UTC, DaisukeShibuya1006 commented
こちらを参考にしました。
https://morizyun.github.io/blog/yard-rails-ruby-gem-document-html/index.html
https://hawksnowlog.blogspot.com/2019/04/getting-started-ruby-yard.html

2021-02-01 05:42 UTC, ymaruyama-bst commented on app/controllers/application_controller.rb
> +  # @return[Object] ログイン中のユーザ
参考
```
# セッションに一致するユーザを返す
# sessionにユーザがない場合や一致するUserがない場合はnilを返し、一致するユーザがあればUser情報を返す
#
# @return [User] ログイン中のユーザ
# @return [nil] 一致するユーザがない場合nil
```

2021-02-01 05:42 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
>      params.require(:task).permit(:title, :text, :deadline, :status, :priority)
クラスがわからなければ`.class`を付けて実際に動かして確認してみるとか
https://docs.ruby-lang.org/ja/latest/method/Object/i/class.html
```
def task_params
  tmp = params.require(:task).permit(:title, :text, :deadline, :status, :priority)
  pp tmp # 値を確認
  pp tmp.class # 値のクラスを確認
  tmp
end
```

2021-02-01 09:20 UTC, DaisukeShibuya1006 commented
@ymaruyama-bst 
ご指摘頂きました箇所を修正しましたので、再度レビューお願い致します。

2021-02-01 09:30 UTC, ShintaroSakai commented on app/controllers/application_controller.rb
> +  # @return[User] ログイン中のユーザ
それぞれのメソッドで引数、返り値の型の定義がおかしいね
前も言った気がする。。。
https://github.com/DaisukeShibuya1006/Task-management-system/pull/21#discussion_r539835241

2021-02-01 09:30 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # title_search, status_search, tasks_sortメソッドを呼び出す
ここの返り値はなしであってますでしょうか??

> title_search, status_search, tasks_sortメソッドを呼び出す

メソッドを呼び出してなにをしているのでしょうか??

2021-02-01 09:30 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @param[ActionController::Parameters] 許可されたパラメータのみ通過
> @param[ActionController::Parameters] 許可されたパラメータのみ通過

@paramは引数を指しているぽいですがこれだとどれになるのでしょうか??
https://hawksnowlog.blogspot.com/2019/04/getting-started-ruby-yard.html#params

2021-02-03 02:36 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @param[ActionController::Parameters] 許可されたパラメータのみ通過
下記のように修正しました！
```
  # 許可されたカラムのみ通過させる
  # @param title[ActionController::Parameters] 許可された'title'を通過
  # @param text[ActionController::Parameters] 許可された'text'を通過
  # @param deadline[ActionController::Parameters] 許可された'deadline'を通過
  # @param status[ActionController::Parameters] 許可された'status'を通過
  # @param priority[ActionController::Parameters] 許可された'priorty'を通過
```

2021-02-03 02:38 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # title_search, status_search, tasks_sortメソッドを呼び出す
private下のコメントと重複しますが、下記のように修正しました！

```
  # title_searchでタスクをタイトルで検索する
  # @return[Task] タイトル検索の結果
  # status_searchでタスクをステータスで検索する
  # @return[Task] ステータス検索の結果
  # タスクを優先度でソートする
  # 優先度が未選択なら、作成日時で降順させる
  # @return[Task] 優先順位のソート結果
```

2021-02-03 03:45 UTC, DaisukeShibuya1006 commented on app/controllers/application_controller.rb
> +  # @return[User] ログイン中のユーザ
丸山さんのYARDを参考にさせて頂きまして、戻り値のクラスが分かった方が良いかと思いますので、@return[Object] ではなく、@return[User]にさせて頂きたいと思いますが、よろしいでしょうか？
https://github.com/DaisukeShibuya1006/Task-management-system/pull/27#discussion_r567573087

2021-02-03 04:00 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # title_search, status_search, tasks_sortメソッドを呼び出す
> private下のコメントと重複しますが

ここで書いたのは呼び出しているメソッドに対してのコメントを書いているからですね
indexメソッドでそれらを呼び出して何をしているかを書いた方がいいと思います

2021-02-03 04:02 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @param[ActionController::Parameters] 許可されたパラメータのみ通過
書き方はあっていますでしょうか??

2021-02-03 04:09 UTC, ShintaroSakai commented on app/controllers/application_controller.rb
> +  # @return[User] ログイン中のユーザを返す
> ログイン中のユーザを返す

これは処理の説明ではないでしょうか??
他も同様

2021-02-03 04:09 UTC, ShintaroSakai commented on app/controllers/sessions_controller.rb
> +  # @return[nil] ログアウト
> @return[nil] ログアウト

これはどういう意味でしょうか??

2021-02-03 04:09 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +      pp @task
ppが残ってますよ

2021-02-03 09:29 UTC, DaisukeShibuya1006 commented
@ShintaroSakai 
レビュー頂きました箇所を修正しましたので、ご確認お願いします！

2021-02-03 10:30 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # title_search, status_search, tasks_sortメソッドを呼び出す
> カレントユーザのタスクをタイトルで検索
検索と一致したタイトルがある場合は該当するタスクを取得し、なければ全件取得
@return[Task] タイトル検索結果

これらは定義もとで書いているので、改めて書く必要はないと思います
> indexメソッドでそれらを呼び出して何をしているかを書いた方がいいと思います

2021-02-03 10:30 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @param[ActionController::Parameters] 許可されたパラメータのみ通過
ここの2つだけ書き方が違うように見えますが、あっていますでしょうか??
https://github.com/DaisukeShibuya1006/Task-management-system/pull/27/files#diff-766c34fd6533171eaf54300c153f89d6002c35c02cfc9c5b219251f85180ad07R16

2021-02-08 01:38 UTC, DaisukeShibuya1006 commented
こちらのご指摘箇所を修正しましたので、ご確認お願い致します。
https://github.com/DaisukeShibuya1006/Task-management-system/pull/27#discussion_r569301196

https://github.com/DaisukeShibuya1006/Task-management-system/pull/27#discussion_r569301240

2021-02-08 01:51 UTC, ymaruyama-bst requested changes
ざっと気になったところにコメントしました。
ご確認をお願いします。

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/application_controller.rb
> +  # ユーザが確認できない場合はUserモデルからidを抽出
一致するユーザが確認できない場合に抽出されるUserモデルのIDってどのIDでしょうか？

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/application_controller.rb
> +end
最終行に改行がないっぽいようですがrubocopって通ってますでしょうか？

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/sessions_controller.rb
> +  # emailが一致しない場合は、ログイン失敗
emailさえ一致すればログイン成功になるのでしょうか？
あとただログイン処理しているだけなのにコメント量が多いので、要点をまとめて簡潔なコメントにしてほしいです。

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/sessions_controller.rb
> +  # @return[User]ログイン
returnの説明がおかしいです。
User == ログインなのでしょうか？

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/sessions_controller.rb
> +  # ログアウト
上の行と逆ではないでしょうか？
ログアウトの内部処理としてセッションを削除しているという説明がある方が適切かと思います。

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/sessions_controller.rb
> +  # @param email[String] 許可されたemail
emailやpasswordは引数として渡されていますでしょうか？

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/sessions_controller.rb
> +    session = params.require(:session).permit(:email, :password)
sessionになにかを代入していますが、その後sessionは使われていないように見えます。
代入する意図を知りたいです。
あとこの場合なにかが返されていそうですがどうでしょうか？

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # タスクのソート
結局のところ、indexってなにをするのでしょうか？
内部で実行されているメソッドの説明を列挙してもしょうがないと思います。

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @return[Task] カレントユーザの作成したタスク
ここの返り値はどこに返されていますでしょうか？

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @param priority[Integer] 許可されたpriorty
ここの引数ってどのように受け取っていますでしょうか？

2021-02-08 01:51 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +    task_params = params.require(:task).permit(:title, :text, :deadline, :status, :priority)
ここで代入している意図が知りたいです。

2021-02-08 03:00 UTC, ShintaroSakai commented on app/controllers/sessions_controller.rb
> +    session = params.require(:session).permit(:email, :password)
どうして変数に入れているのでしょうか??

2021-02-08 03:00 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # 許可されたカラムのみ通過
> 許可されたカラムのみ通過
titleが入力されているか確認
titleが未入力の場合は作成失敗

概要のコメントに違和感があります
requireとpermitはそれぞれを何をしているのでしょうか??

2021-02-08 03:00 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
returnの説明も書いて欲しいです

2021-02-08 03:01 UTC, ShintaroSakai commented on app/controllers/sessions_controller.rb
> +    session = params.require(:session).permit(:email, :password)
すみません、既にコメントされてましたね

2021-02-08 03:13 UTC, DaisukeShibuya1006 commented on app/controllers/sessions_controller.rb
> +    session = params.require(:session).permit(:email, :password)
デバッグしたときの変数がそのままになっていましたので、こちらは不要です。すみませんが、下記の変数も不要です。
https://github.com/DaisukeShibuya1006/Task-management-system/pull/27#discussion_r571740187

2021-02-08 04:41 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # 許可されたカラムのみ通過
requireでTaskモデルを定めて、permitで許可されたカラムのデータのみを取得します。

2021-02-08 08:11 UTC, DaisukeShibuya1006 commented on app/controllers/application_controller.rb
> +  # @return[User] ログイン中のユーザを返す
こちら修正しました。

2021-02-08 08:13 UTC, DaisukeShibuya1006 commented on app/controllers/sessions_controller.rb
> +  # @return[nil] ログアウト
こちら修正しました。

2021-02-08 08:32 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # タスクのソート
indexのコメントを変更しました。
`# @return[Task]タスクの検索結果`

2021-02-09 01:59 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
returnの説明を下記のように変更しました。
`# @return[Task]タスクの検索結果`

2021-02-09 01:59 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +    task_params = params.require(:task).permit(:title, :text, :deadline, :status, :priority)
すみませんが、こちらの代入は誤りでした。

2021-02-09 02:18 UTC, DaisukeShibuya1006 commented on app/controllers/sessions_controller.rb
> +  # ログアウト
下記のように変更しました。
```
# ログアウト
# @return[Task]タスクの検索結果
```

2021-02-09 02:20 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @param[ActionController::Parameters] 許可されたパラメータのみ通過
下記のように変更しました。
```
# ログイン中のユーザか確認
# 未ログインならば、ログイン画面に移行
```

2021-02-09 02:28 UTC, DaisukeShibuya1006 commented on app/controllers/application_controller.rb
> +end
すみません、こちら消し忘れていました。不要な箇所を削除しました。

2021-02-09 02:29 UTC, DaisukeShibuya1006 commented on app/controllers/sessions_controller.rb
> +  # emailが一致しない場合は、ログイン失敗
下記のように修正しました。
```
# ログイン
# emailとpasswordが一致していたら、sessionにuser.idを格納
```

2021-02-09 02:31 UTC, DaisukeShibuya1006 commented on app/controllers/sessions_controller.rb
> +  # @return[User]ログイン
Userは返していませんので、 `# @return[User]ログイン`を削除しました。

2021-02-09 02:32 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task] カレントユーザの作成したタスク
返り値はTaskではありませんので、下記のコメントは削除しました。 
` # @return[Task] カレントユーザの作成したタスク
`

2021-02-09 02:34 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @param priority[Integer] 許可されたpriorty
こちらですが引数は受け取っていませんので、`@param`を削除し、下記のように修正しました。

```
# パラメータの認証
# @return[ActionController::Parameters] 許可されたパラメータ
```

2021-02-09 02:59 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
メソッドの概要が抜けてます

2021-02-09 02:59 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @param[ActionController::Parameters] 許可されたパラメータのみ通過
コメントする場所間違ってない??

2021-02-09 03:02 UTC, ymaruyama-bst requested changes
一旦

2021-02-09 03:02 UTC, ymaruyama-bst commented on app/controllers/application_controller.rb
> +  # ユーザが確認できない場合はUser.idと一致するユーザを抽出
> ユーザが確認できない場合はUser.idと一致するユーザを抽出

なにと一致するかがないので言葉として違和感があります。
セッションに持っているuser_idに紐づくユーザとか？

2021-02-09 03:02 UTC, ymaruyama-bst commented on app/controllers/application_controller.rb
> +  # @return[User] ログイン中のユーザ
> @return[User] ログイン中のユーザ

返すのは自身のUser情報かと思います。
ログイン中のユーザだと他にログインしているユーザも返されるように捉えられるので避けたほうがいいかと。

2021-02-09 03:02 UTC, ymaruyama-bst commented on app/controllers/application_controller.rb
> +  # sessionに一致するユーザを確認
「確認」だとなにをしているのかが不明瞭に感じます。
登録されている自身のユーザ情報を取得とか？

2021-02-09 03:02 UTC, ymaruyama-bst commented on app/controllers/sessions_controller.rb
> +  # パラメータの認証
「認証」は言葉の意味を考えると不適当に思いますがどうでしょうか？

2021-02-09 03:02 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @return[Task] タスクのインスタンス
`@return [Task]` でタスクのインスタンスを返すことがわかっているのですから説明書かなくてもいいんじゃないですかね？

2021-02-09 03:02 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # カレントユーザがタスクを作成
カレントユーザが作るとどうなるのでしょうか？

2021-02-09 03:13 UTC, ShintaroSakai commented on app/controllers/sessions_controller.rb
> +  # emailとpasswordが一致していたら、sessionにuser.idを格納
丸山さんの例を参考に
条件分岐で分かれているならそれぞれで書いた方がいいと思います

https://github.com/DaisukeShibuya1006/Task-management-system/pull/27#discussion_r567573087

> セッションに一致するユーザを返す
sessionにユーザがない場合や一致するUserがない場合はnilを返し、一致するユーザがあればUser情報を返す

2021-02-09 03:15 UTC, DaisukeShibuya1006 commented on app/controllers/application_controller.rb
> +  # ユーザが確認できない場合はUser.idと一致するユーザを抽出
確かに自分で読んでておかしい日本語だと理解できました。
下記のような感じに変更させていただきます！
`# ユーザが確認できない場合はUser.idとセッションが持っているuser_idに紐づくユーザを抽出`

2021-02-09 03:18 UTC, DaisukeShibuya1006 commented on app/controllers/application_controller.rb
> +  # @return[User] ログイン中のユーザ
`# @return[User] 自身のユーザ情報`に修正させていただきます！

2021-02-09 03:20 UTC, DaisukeShibuya1006 commented on app/controllers/application_controller.rb
> +  # sessionに一致するユーザを確認
確かに確認ではなく取得している処理ですよね。
`# 登録されている自身のユーザ情報を取得`で修正します！

2021-02-09 03:26 UTC, DaisukeShibuya1006 commented on app/controllers/sessions_controller.rb
> +  # パラメータの認証
「認証」だとユーザのIDやパスワードを確認するような意味合いなので、普通に`パラメータの許可`が適当そうですね。修正致します！

2021-02-09 04:13 UTC, ymaruyama-bst commented on app/controllers/application_controller.rb
> +  # ユーザが確認できない場合はUser.idと一致するユーザを抽出
> User.idとセッションが持っているuser_idに紐づくユーザ

「User.id（A）」と「セッションが持っているuser_id（B）」に紐づく「ユーザ（C）」
これだと言葉的に、A==C && B==Cになりません？
「User.id（A）」のUserが「ユーザ（C）」とイコールなのでAの部分は不要だと思いますし、
もしAの部分を書くのであれば「User.idとセッションが持っているuser_idが一致するユーザ」としたほうがいい気がします。
まぁ言葉なので他の人にも聞いてみたほうがいい気もしますが。

2021-02-09 05:44 UTC, DaisukeShibuya1006 commented on app/controllers/application_controller.rb
> +  # ユーザが確認できない場合はUser.idと一致するユーザを抽出
AとBが一致することを書くべきだったところをAとBがそれぞれCと一致していると書いてしまっていたと言うことですね。

こちらに修正致します。「User.idとセッションが持っているuser_idが一致するユーザが正しいですね。」

2021-02-09 06:09 UTC, DaisukeShibuya1006 commented on app/controllers/sessions_controller.rb
> +  # emailとpasswordが一致していたら、sessionにuser.idを格納
このような感じでよろしいでしょうか？
```
# ログイン
# emailとpasswordが一致する場合、sessionにuser.idを格納
# emailとpasswordが一致しない場合、ログイン不可
```

2021-02-09 06:31 UTC, ShintaroSakai commented on app/controllers/sessions_controller.rb
> +  # emailとpasswordが一致していたら、sessionにuser.idを格納
- やっていることとしてはsessionにuser.idを格納だけでしょうか??
- ログイン不可だと具体的にどうなるかがわかりない気がします
エラーメッセージが返るのか、元の画面に戻るのかとか

2021-02-09 07:02 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task] タスクのインスタンス
確かにコンパクトですよね。他にも説明とreturnが重複しているコメントありますが、こちらってどうするべきでしょうか？

@ShintaroSakai酒井さん的には概要書いた方が良い感じですよね？


 https://github.com/DaisukeShibuya1006/Task-management-system/pull/27#discussion_r572535528

2021-02-15 01:19 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # カレントユーザがタスクを作成
「カレントユーザがタスクを作成」というよりも「カレントユーザがタスクを投稿」の方が適切な感じでしょうか？

2021-02-15 01:26 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # カレントユーザがタスクを作成
「カレントユーザが」と明示する意図が何なのかなと思いまして。

2021-02-15 01:27 UTC, DaisukeShibuya1006 commented on app/controllers/sessions_controller.rb
> +  # emailとpasswordが一致していたら、sessionにuser.idを格納
「sessionにuser_idを格納」== ログインなので良いと思います。
「emailとpasswordが一致する場合」という表現を使うとemailとpasswordが一致しない場合はsessionにuser_idを格納しないと取れますので、下記の書き方が適切だと思います。
```
# ログイン
# emailとpasswordが一致する場合、sessionにuser.idを格納
```

2021-02-15 01:28 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @return[Task] タスクのインスタンス
> 酒井さん的には概要書いた方が良い感じですよね？

ここは処理が単純だからreturnだけでいいかもしれない
でもこっちは書いた方がいいと思う
#27 (comment)

2021-02-15 01:33 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task] タスクのインスタンス
確かにこちら書いた方が良かったですね、今理解できました。
```
# タスクの検索
# @return[Task]タスクの検索結果
```

2021-02-15 01:38 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # カレントユーザがタスクを作成
current_userがコードに含まれているので、書いた方が良いと思いましたが、重要度低かったですかね？
`@task = current_user.tasks.new(task_params)`

下記の書き方でよろしいでしょうか？
`#タスクを投稿`

2021-02-15 01:48 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
下記のように修正しました！
```
# タスクの検索
# @return[Task]タスクの検索結果
```

2021-02-15 02:13 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @return[Task] タスクのインスタンス
概要（メソッドの説明）は書くべきで@returnはTask自体がタスクのインスタンスを示しているのでわざわざ「タスクのインスタンス」と明示する必要はないと思います。

2021-02-15 02:16 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
概要は検索結果の一覧を「取得」まで書いてしまって、@returnはTaskだけだとTaskが一つ返されているように見えるのであっているか確認してほしいです。
返されているのは検索結果の「一覧」だと思うので、Arrayとかになってないですかね？

2021-02-15 03:58 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task] タスクのインスタンス
こちら以外にも@returnに不要なコメントを記載していましたので、合わせて削除しました。

2021-02-15 04:04 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
デバッグすると戻り値が配列でしたので、Arrayが正しかったです。こちら修正しました。

2021-02-15 04:19 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @return[Task] タスクのインスタンス
> こちら以外にも@returnに不要なコメントを記載していましたので、合わせて削除しました。

- @returnの説明は不要という意味ではなくて、ここで行っているのはインスタンスの生成のみなので、
`@return [Task]`だけで理解できるという意味ですね
- 他のメソッドの返値はインスタンスを返してても、その中身が違いますよね

だから、他は残しておくべきです

2021-02-15 04:23 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
IMO
配列の中身も書いてあるとわかりやすいと思いました

2021-02-15 04:25 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # タスクを優先度でソート
indexのクラスのコメントを書き直したのなら
こっちも書き直した方がいいです

2021-02-15 05:37 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
下記のように修正しました！
`@return [Array<tasks>]`

2021-02-15 05:47 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # タスクを優先度でソート
` @return [Array<tasks>]`

2021-02-15 06:25 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task] タスクのインスタンス
ご説明していただきましてありがとうございます。
`@return`コメントを元に戻しました。

2021-02-15 06:47 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
`@return [Array<Task>]`がいいと思います.
配列の変数は複数形になるため、Array<tasks>だと配列の中に配列があると勘違いしてしまうからです

2021-02-15 06:55 UTC, ShintaroSakai reviewed
レビュー出す前に見直しをしましょう

2021-02-15 06:55 UTC, ShintaroSakai commented on app/controllers/tasks_controller.rb
> +  # @return [Array<tasks>] タイトルの検索結果
@returnの説明で検索はタイトルだけじゃないので
タスクの検索結果の方がいいと思います

2021-02-15 06:55 UTC, ShintaroSakai commented on app/controllers/sessions_controller.rb
> +
ここ2行空いてませんか??

2021-02-15 07:30 UTC, DaisukeShibuya1006 commented on app/controllers/sessions_controller.rb
> +
すみません、こちら埋めました。

2021-02-15 07:32 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # @return[Task]
なるほど納得できました！ありがとうございます。こちらも修正しました！

2021-02-15 07:48 UTC, ShintaroSakai approved these changes
LGTM

2021-02-15 07:51 UTC, ymaruyama-bst reviewed
一箇所だけ。
ここ直したら大丈夫だと思います。

2021-02-15 07:51 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # タスクを優先度でソート
> 優先度が未選択なら、作成日時で降順

作成日時でソートするパターンがあるならば概要から優先度を抜いたほうがいいと思います。

2021-02-15 07:51 UTC, ymaruyama-bst commented on app/controllers/tasks_controller.rb
> +  # タスクを優先度でソート
`@return`のところの説明も同じく

2021-02-15 07:57 UTC, DaisukeShibuya1006 commented on app/controllers/tasks_controller.rb
> +  # タスクを優先度でソート
こちら修正しました！

2021-02-15 07:58 UTC, ymaruyama-bst approved these changes
LGTM

2021-02-15 07:59 UTC, ymaruyama-bst commented
問題なければマージして、23のブランチの方にも取り込んでください。

2021-02-15 07:59 UTC, DaisukeShibuya1006 commented
承知しました！

2021-02-15 08:01 UTC, merged